module SkelDeclaration where

-- Haskell module generated by the BNF converter

import AbsDeclaration
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Program topdefs -> failure x
transTopDef :: TopDef -> Result
transTopDef x = case x of
  FnDef type_ ident args block -> failure x
  GlobDecl type_ items -> failure x
  GlobFinDecl type_ items -> failure x
  StructDef ident structdecls -> failure x
transStructDecl :: StructDecl -> Result
transStructDecl x = case x of
  Field type_ ident -> failure x
transStructField :: StructField -> Result
transStructField x = case x of
  StructField ident -> failure x
transArg :: Arg -> Result
transArg x = case x of
  Arg type_ ident -> failure x
transBlock :: Block -> Result
transBlock x = case x of
  Block stmts -> failure x
transStmt :: Stmt -> Result
transStmt x = case x of
  Empty -> failure x
  BStmt block -> failure x
  Decl type_ items -> failure x
  DeclFinal type_ items -> failure x
  Ass ident expr -> failure x
  ArrAss ident integer expr -> failure x
  StructAss structfields expr -> failure x
  Incr ident -> failure x
  Decr ident -> failure x
  Ret expr -> failure x
  VRet -> failure x
  Cond expr stmt -> failure x
  CondElse expr stmt1 stmt2 -> failure x
  While expr stmt -> failure x
  SExp expr -> failure x
  FnInDef type_ ident args block -> failure x
  ConstFor type_ ident expr1 expr2 stmt -> failure x
  Break -> failure x
  Continue -> failure x
  Try block catchs -> failure x
  Throw expr -> failure x
transItem :: Item -> Result
transItem x = case x of
  NoInit ident -> failure x
  Init ident expr -> failure x
transCatch :: Catch -> Result
transCatch x = case x of
  Catch arg block -> failure x
transType :: Type -> Result
transType x = case x of
  Int -> failure x
  Bool -> failure x
  Void -> failure x
  StructType ident -> failure x
  FuncType types type_ -> failure x
  ArrayType type_ -> failure x
transExpr :: Expr -> Result
transExpr x = case x of
  EVar ident -> failure x
  ENull -> failure x
  ELitInt integer -> failure x
  ELitTrue -> failure x
  SLitString string -> failure x
  ELitFalse -> failure x
  EApp ident exprs -> failure x
  EArray exprs -> failure x
  EArrayIdx ident integer -> failure x
  EField structfields -> failure x
  ELambda args type_ block -> failure x
  Neg expr -> failure x
  Not expr -> failure x
  EMul expr1 mulop expr2 -> failure x
  EAdd expr1 addop expr2 -> failure x
  ERel expr1 relop expr2 -> failure x
  EAnd expr1 expr2 -> failure x
  EOr expr1 expr2 -> failure x
transAddOp :: AddOp -> Result
transAddOp x = case x of
  Plus -> failure x
  Minus -> failure x
transMulOp :: MulOp -> Result
transMulOp x = case x of
  Times -> failure x
  Div -> failure x
  Mod -> failure x
transRelOp :: RelOp -> Result
transRelOp x = case x of
  LTH -> failure x
  LE -> failure x
  GTH -> failure x
  GE -> failure x
  EQU -> failure x
  NE -> failure x

